stages:
  - build
  - test
  - deploy
  

before_script:
  - chmod +x ./backend/demo/gradlew
  - export GRADLE_USER_HOME=`pwd`/backend/demo/.gradle

build:
  stage: build
  image: gradle:jdk11-alpine
  script: 
    - cd ./backend/demo
    - ./gradlew --build-cache assemble
    - cd ..
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths: 
      - build
      - .gradle

test-backend:
  stage: test
  image: gradle:jdk11-alpine
  script:
    - cd backend/demo
    - ./gradlew test
    - cd ..
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths: 
      - build
      - .gradle

heroku-production:
  stage: deploy
  image: ruby:latest
  needs: ["build"]
  script:
    - cd backend/demo
    - gem install dpl
    - dpl --app=swtp-2021-12-production --provider=heroku --api-key=$HEROKU_API_KEY
    - cd ..
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: on_success
    - allow_failure: false

#heroku-staging:
#  stage: deploy
#  image: ruby:latest
#  needs: ["build"]
#  script:
#    - cd backend/demo
#    - gem install dpl
#    - dpl --app=swtp-2021-12-staging --provider=heroku --api-key=$HEROKU_API_KEY
#    - cd ..

